retailco_dbt:
  target: dev

  outputs:
    dev:
      type: postgres
      host: warehouse_db
      port: 5432
      user: postgres
      password: postgres123
      dbname: warehouse
      schema: analytics
      threads: 4
